default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  <<: *default
  encoding: unicode
  database: project_development
  username: root
  password:
test:
  <<: *default
  encoding: unicode
  database: project_test
  username: root
  password:
production:
  <<: *default
  encoding: unicode
  database: project_test
  username: root
  password:
